### PR TITLE
Cleanup unused

### PR DESCRIPTION
**Pull request by SvMak**
Related to https://github.com/jhipster/generator-jhipster/issues/27770

### CODE REVIEW

**Comment by mraible** [comment]
What do you mean by unused? Are they currently not linked to on the website? If we remove these, will it cause 404s?

**Comment by SvMak** [comment]
> What do you mean by unused? Are they currently not linked to on the website? If we remove these, will it cause 404s?

These folders were left over from the previous split, I didn't touch them because I try not to delete anything that doesn't concern the issue.

Links to these versions of the documentation will be added to the https://github.com/jhipster/documentation-archive-v1-to-v5 repo, these are duplicates

Screenshot from 2024-11-05 17-00-40

**Comment by mraible** [comment]
@SvMak This seemed to have worked since the GitHub actions passed. However, there are two v8.7.3 folders at https://www.jhipster.tech/documentation-archive/. I'll remove the 2nd one.

**Comment by mraible** [comment]
Hmmm, there's only one v8.7.3 folder in the Git repo. Not sure how to remove the 2nd from the website.

Screenshot 2024-11-05 at 10 35 23

**Comment by SvMak** [comment]
That's just link in the index.html

Screenshot from 2024-11-05 18-38-48

**Comment by mraible** [comment]
Thanks! I thought the directory listing was generated, not a simple index.html file. 😅 Fixed!

**Comment by SvMak** [comment]
> Thanks! I thought the directory listing was generated, not a simple index.html file. 😅 Fixed!

Super! Thanks a lot!

**Pull request merged**
