### PR TITLE
Move legacy documentation to a separate repository

### PR DESCRIPTION
**Pull request by anarsultanov**
Related to https://github.com/jhipster/generator-jhipster/issues/18318
This PR can be merged when https://github.com/jhipster/documentation-archive-v1-to-v5/pull/1 is merged and the GitHub pages are configured in that repository.

### CODE REVIEW

**Comment by deepu105** [comment]
other PR merged and GH pages setup

**Comment by deepu105** [comment]
cc @pascalgrimaud @PierreBesson  does this look good to you?

**Comment by pascalgrimaud** [comment]
I can't say, until it's merged, so let's try?

**Comment by PierreBesson** [comment]
Yes looks good to me

**Pull request merged**
